[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "toggle_special",
]

[scratchpads.term]
command = "alacritty --class alacritty_dropdown"
animation = "fromTop"
unfocus = "hide"
excludes = "*"
lazy = true

[scratchpads.volume]
command = "pavucontrol --class volume_sidemenu"
animation = "fromRight"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
